const names = {
  TOGGLE_DROPDOWN: "TOGGLE_DROPDOWN",
  SELECT_ITEM: "SELECT_ITEM",
  UNSELECT_ITEM: "UNSELECT_ITEM",
  UPDATE_CURRENT_ITEM: "UPDATE_CURRENT_ITEM",
  UPDATE_SIZE: "UPDATE_SIZE",
  INCREMENET: "INCREMENET",
  DECREMENT: "DECREMENT",
  SELECT_SUPLUMENT: "SELECT_SUPLUMENT",
  UNSELECT_SUPLUMENT: "UNSELECT_SUPLUMENT",
  INCREMENET_ORDER_ITEM: "INCREMENET_ORDER_ITEM",
  DECREMENT_ORDER_ITEM: "DECREMENT_ORDER_ITEM",
  CLEAR_CURRENT_ITEM: "CLEAR_CURRENT_ITEM",
  MOVE_ITEM: "MOVE_ITEM",
  EDIT_ORDER_ITEM_PRICE: "EDIT_ORDER_ITEM_PRICE",
  DELETE_ORDER_ITEM: "DELETE_ORDER_ITEM",
  TOGGLE_RETARD: "TOGGLE_RETARD",
  INSERT_RETARD_TIME: "INSERT_RETARD_TIME",
  SELECT_ORDER_TYPE: "SELECT_ORDER_TYPE",
  SELECT_TYPE_INFO: "SELECT_TYPE_INFO",
  CALCULATE_TOTAL: "CALCULATE_TOTAL",
};

export default names;
