const names = {
  EXTEND_DROPDOWN: "EXTEND_DROPDOWN",
  SELECT_ITEM: "SELECT_ITEM",
  UNSELECT_ITEM: "UNSELECT_ITEM",
  UPDATE_CURRENT_ITEM: "UPDATE_CURRENT_ITEM",
  UPDATE_SIZE: "UPDATE_SIZE",
  INCREMENET: "INCREMENET",
  DECREMENT: "DECREMENT",
};

export default names;
