const names = {
  EXTEND_DROPDOWN: "EXTEND_DROPDOWN",
  SELECT_ITEM: "SELECT_ITEM",
  UNSELECT_ITEM: "UNSELECT_ITEM",
  UPDATE_CURRENT_ITEM: "UPDATE_CURRENT_ITEM",
  UPDATE_SIZE: "UPDATE_SIZE",
  INCREMENET: "INCREMENET",
  DECREMENT: "DECREMENT",
  SELECT_SUPLUMENT: "SELECT_SUPLUMENT",
  UNSELECT_SUPLUMENT: "UNSELECT_SUPLUMENT",
};

export default names;
